sonar.projectKey=Fridongraal_ICSCalculadora
sonar.organization=fridongraal

sonar.python.version=3.11
sonar.sources=calculadora.py
sonar.tests=test_calculadora.py
sonar.exclusions=venv/**,__pycache__/**,.pytest_cache/**

sonar.python.coverage.reportPaths=coverage.xml